server:
  port: 9000

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/backend
    username: root
    password: devpass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
